name: WoMM

model:
  _target_: pl_modules.womm.WoMM
  encoder: # Multi-modal model to be trained
    _target_: models.mmfusion.MMFusion
    embed_dim: 512
    fusion: "concat"
    pool: "cls"
    n_heads: 8
    n_layers: 1
    add_bias_kv: False
    dropout: 0

  projection: # Projection head
    _target_: pl_modules.womm.WoMM._build_mlp
    in_dim: ${model.model.encoder.embed_dim} # MM encoder dimension
    mlp_dim: 512 # Hidden dim of MLP projection head
    out_dim: 256 # Output embed dim of MLP projection head

  loss_kwargs:
    reconstruction: "cosine"       # 'mse' 'l1' 'huber' 'rbf' 'cosine'
    regularization: "neg-samples"    # 'sigreg' 'vicreg' 'visreg' 'neg-samples' 'sem-aware' 'neg-samples-multi'
    reg_weight: 0.5
    temperature: 0.1
    sigma_max: 2.0
    sigma_min: 0.5
    K: 4096
    weights: null
    stop_grad: False
    vicreg_inv_coeff: 25.0
    vicreg_std_coeff: 25.0
    vicreg_cov_coeff: 1.0
    use_geco: True
    geco_warmup_epochs: 25
    geco_tolerance_margin: 0.95
    geco_alpha: 0.90
    geco_clamp_min: 0.98
    geco_clamp_max: 1.02
    geco_updates_per_epoch: 10
    steps_per_epoch: 0             
    sim_ema_short_alpha: 0.5
    sim_ema_long_alpha: 0.9
    sim_degradation_tolerance: 0.01