name: WoMM

model:
  _target_: pl_modules.womm.WoMM
  encoder: # Multi-modal model to be trained
    _target_: models.mmfusion.MMFusion
    embed_dim: 512
    fusion: "concat"
    pool: "cls"
    n_heads: 8
    n_layers: 1
    add_bias_kv: False
    dropout: 0

  projection: # Projection head
    _target_: pl_modules.womm.WoMM._build_mlp
    in_dim: ${model.model.encoder.embed_dim} # MM encoder dimension
    mlp_dim: 512 # Hidden dim of MLP projection head
    out_dim: 256 # Output embed dim of MLP projection head

  loss_kwargs:
    reconstruction: "mse"       # 'mse' 'l1' 'huber' 'rbf' 'cosine'
    regularization: "sigreg"    # 'sigreg' 'vicreg' 'visreg' 'neg-samples'
    reg_weight: 0.05
    temperature: 0.1
    sigma_max: 2.0
    sigma_min: 0.5
    K: 4096
    weights: null
    stop_grad: False